'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("zlibVBNET.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NumBits must be between 0 and 64..
        '''</summary>
        Friend ReadOnly Property BitStream_NumBits_OutOfRange() As String
            Get
                Return ResourceManager.GetString("BitStream_NumBits_OutOfRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid number of distance codes..
        '''</summary>
        Friend ReadOnly Property Decompressor_InflateDynamic_InvalidNumberOfDistanceCodes() As String
            Get
                Return ResourceManager.GetString("Decompressor_InflateDynamic_InvalidNumberOfDistanceCodes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid number of literal length codes..
        '''</summary>
        Friend ReadOnly Property Decompressor_InflateDynamic_InvalidNumberOfLiteralLengthCodes() As String
            Get
                Return ResourceManager.GetString("Decompressor_InflateDynamic_InvalidNumberOfLiteralLengthCodes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error in compressed data. Block Length did not passed verification..
        '''</summary>
        Friend ReadOnly Property Decompressor_InflateNoCompression_DataBlockLengthDidNotPassedVerification() As String
            Get
                Return ResourceManager.GetString("Decompressor_InflateNoCompression_DataBlockLengthDidNotPassedVerification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid compressed stream. No data found..
        '''</summary>
        Friend ReadOnly Property Decompressor_InvalidCompressedStreamNoDataFound() As String
            Get
                Return ResourceManager.GetString("Decompressor_InvalidCompressedStreamNoDataFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Encrypted compressed streams are not supported..
        '''</summary>
        Friend ReadOnly Property Decompressor_UnGzip_EncryptedStream() As String
            Get
                Return ResourceManager.GetString("Decompressor_UnGzip_EncryptedStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This compressed GZIP file is a continuation of a previous file. Unable to continue..
        '''</summary>
        Friend ReadOnly Property Decompressor_UnGzip_InvalidContinuation() As String
            Get
                Return ResourceManager.GetString("Decompressor_UnGzip_InvalidContinuation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid GZIP file or stream..
        '''</summary>
        Friend ReadOnly Property Decompressor_UnGzip_InvalidGzipFileStream() As String
            Get
                Return ResourceManager.GetString("Decompressor_UnGzip_InvalidGzipFileStream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Stream and File Mix. Some Data was decompressed. Check Files Array or UnccompressedStream Property..
        '''</summary>
        Friend ReadOnly Property Decompressor_UnGzip_InvalidStreamAndFileMix_SomeDataWasDecompressed() As String
            Get
                Return ResourceManager.GetString("Decompressor_UnGzip_InvalidStreamAndFileMix_SomeDataWasDecompressed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reserved bit set in FLAGS, a different version of the zlibVB.NET is required..
        '''</summary>
        Friend ReadOnly Property Decompressor_UnGzip_ReservedBitSet() As String
            Get
                Return ResourceManager.GetString("Decompressor_UnGzip_ReservedBitSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LengthCodeArray is null or empty..
        '''</summary>
        Friend ReadOnly Property HuffmanTable_GenerateTable_LengthCodeArrayIsNull() As String
            Get
                Return ResourceManager.GetString("HuffmanTable_GenerateTable_LengthCodeArrayIsNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Compressed Data. More codes than bits..
        '''</summary>
        Friend ReadOnly Property HuffmanTable_GenerateTable_MoreCodesThanBits() As String
            Get
                Return ResourceManager.GetString("HuffmanTable_GenerateTable_MoreCodesThanBits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of bits must be between 0 and 64..
        '''</summary>
        Friend ReadOnly Property Mask_BitMask_OutOfRangeException() As String
            Get
                Return ResourceManager.GetString("Mask_BitMask_OutOfRangeException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HexChar must be between one of the following characters 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F..
        '''</summary>
        Friend ReadOnly Property Mask_HexMask_Char_OutOfRangeException() As String
            Get
                Return ResourceManager.GetString("Mask_HexMask_Char_OutOfRangeException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HexCode must be between 0 and 15 (0x0 and 0xF)..
        '''</summary>
        Friend ReadOnly Property Mask_HexMask_OutOfRangeException() As String
            Get
                Return ResourceManager.GetString("Mask_HexMask_OutOfRangeException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attempt to read after the end of stream..
        '''</summary>
        Friend ReadOnly Property ReadPastEnd_Message() As String
            Get
                Return ResourceManager.GetString("ReadPastEnd_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown compression method..
        '''</summary>
        Friend ReadOnly Property UnknownCompressionMethod_Message() As String
            Get
                Return ResourceManager.GetString("UnknownCompressionMethod_Message", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
